name: salbp
channels:
  - conda-forge
  - plotly
dependencies:
    - graphviz
    - numpy
    - pandas
    - pip
    - plotly
    - plotly-orca
    - psutil
    - python-graphviz
    - python>=3.5
    - nbformat
    - xlrd
    - pip:
      - ortools